import React from "react";
import StoreProvider from "./StoreProvider";
import type { Metadata } from "next";
import Authentication from "../authentication";

import "./globals.css";
import "../styles/global.scss";

export const metadata: Metadata = {
  title: "User Data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Authentication />
      <html lang="en">
        <body>
          <StoreProvider>{children}</StoreProvider>
        </body>
      </html>
    </>
  );
}
